server:
  port: 8080

---
spring:
  config:
    import: development.yml
    activate:
      on-profile: dev
---
spring:
  config:
    import: userapplicationtesting.yml
    activate:
      on-profile: uat