server:
  port: 8080

oracle-database:
  oracle-db-url: "dummy"
  oracle-db-driver: "dummy"
postgres-database:
  postgres-db-url: "dummy"
  postgres-db-driver: "dummy"

---
spring:
  config:
    import: development.yml
    activate:
      on-profile: dev
---
spring:
  config:
    import: userapplicationtesting.yml
    activate:
      on-profile: uat